### ISSUE TITLE
Authenticated vs Unauthenticated root

### ISSUE THREAD

**Issue by heratyian** [appdev-lessons/authentication-with-devise#1]
Going through final projects, I wish we had mentioned [how to define a different root route for logged out users](https://github.com/heartcombo/devise/wiki/How-To:-Define-a-different-root-route-for-logged-out-users). We should consider adding it here.

**Comment by bpurinton** [comment]
I like this idea, and it would be an easy section to slot in to this guide. I will work on that.

**Comment by bpurinton** [comment]
https://github.com/appdev-lessons/authentication-with-devise/commit/373c0bd72589819c5f4de5d6c404d600c8542505
